apiVersion: v1
kind: Pod
metadata:
  name: cluster-pod
  labels:
    name: myapp
    type: back-end
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
