apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx-deployment
    tier: back-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
  replicas: 6
  selector:
        matchLabels:
          app: nginx
