apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod   
  labels:
    app: myapp
    name: front-end
spec:
  containers:
  - name: ngnix-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
