apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
    - name: nginx-cn
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3000
